#development:
#  dialect: mysql
#  database: widgets
#  user: root
#  password: admin123
#  host: 127.0.0.1
#  pool: 5

development:
  dialect: postgres
  database: usualstore
  user: postgres
  password: password
  host: localhost
  port: 5432
  sslmode: disable
