CREATE TABLE tokens
(
    id         INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id    INTEGER UNSIGNED NOT NULL,
    name       VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL UNIQUE,
    token_hash VARBINARY(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
